### ISSUE TITLE
请教下私有maven后，源码如何管理？

### ISSUE THREAD

**Issue by xiaobaDev** [luckybilly/OKDALM#1]
楼主你好，我们项目结构差不多，现在也在做私有maven的工作，但是如何有效地管理上传到maven之后源码呢？
比如登录模块，我们的模块叫app.login，这个模块源码你们会单独放个git的仓库吗？
抽取出去之后，源码的修改和调试如何有效进行呢？

**Comment by luckybilly** [comment]
你好，很高兴OKDALM能给你提供帮助。

简单介绍一下我们源码管理的方式变化过程：
我们先后经历了以下几个阶段（每个工程一个git地址）：
1. 单个业务线的所有项目代码全部在一个工程中
- app之间可以复用工程内部的lib module
- 业务线之间通过copy公共module代码到自身工程内进行复用
2. 公共module全部抽取到一个CommonLib中，各业务线工程都引用CommonLib工程以实现复用。实现方式： http://www.tuicool.com/articles/7JfQV3
3. CommonLib中的module发布到maven私服（我就是在此阶段写的这个OKDALM工具）
4. 随着android源码的不断封装和抽象，CommonLib中的module越来越多，于是进行了逻辑分层，废弃CommonLib，新创建了3个工程（意味着新增3个git）
5. 后来为每个封装模块分配了owner，为了更方便的进行版本管理和权限控制，我们引入了repo来进行管理，repo管理一个工程，里面的每个module都有自己的git地址

关于调试：
1. module开发、修改期间，module的owner在module所在的工程（Project）中创建demo的app module，通过module依赖的方式引用，可以比较方便的进行源码测试，编译速度快，且不受其它模块影响
2. module应用期间，调试方式跟使用其它开源库一样

希望能对你有帮助

**Comment by xiaobaDev** [comment]
调试这块想法一致
我们现在在经历这一步，分离臃肿的CommonLib。
现状：所有子业务模块用到的通用功能，比如较为通用的UI、用户信息、底层库统统都在CommonLib里，包括
初步想法是抽离一个底层库：网络图片缓存等；一个共享信息库：比如用户信息等单例；再把UI这块，复用不多的，抽离到子业务中，再按照大体作用的划分，分离出几个颗粒略大的UI组件支持库（这一步比需要考虑的比较多）。
朋友你那块逻辑分层的是怎么在项目中开展的呢？

**Comment by luckybilly** [comment]
抱歉，回复晚了。我们是按照模块的通用性来进行逻辑分层的：
1. 跟业务无关的库（理论上适用于所有项目的库）
2. 公司所有项目通用的库
3. 各业务线所有app通用的库（基于业务特点进行了封装）

BTW， 我现在用组件化开发框架进行项目架构，基于组件进行开发，现已开源： https://github.com/luckybilly/CC
