### ISSUE TITLE
moudle name 使用.号作为分割符的时候，version提示找不到属性

### ISSUE THREAD

**Issue by xiaobaDev** [luckybilly/OKDALM#2]
compile group:maven_groupId, name:'app.login', version: app.login

提示找不到app属性

**Comment by luckybilly** [comment]
你可以使用下面这些方式来fix：
compile "${maven_groupId}:app.login:${getProperty("app.login")}"
or
compile group: maven_groupId, name: 'app.login', version: getProperty("app.login")

不过还是建议不要用.号来作为分隔符，建议使用下横线‘_’

**Comment by xiaobaDev** [comment]
用app.login主要是为下一步插件化框架small做准备，那框架的命名就是这种app.***; lib.***命名的
谢谢朋友回答
